promtail:
  enabled: true
loki:
  image:
    tag: 2.9.3
  isDefault: false
  auth_enabled: false
  persistence:
    enabled: false
config:
  table_manager:
  retention_deletes_enabled: true
  retention_period: 720h
