grafana:
  admin:
    existingSecret: kube-prometheus-stack-secret
    userKey: GRAFANA_ADMIN_USER
    passwordKey: GRAFANA_ADMIN_PASSWORD
  # sidecar:
  #   dashboards:
  #     enabled: true
  #     label: grafana_dashboard
  #     folderAnnotation: grafana_folder
  #     provider:
  #       allowUiUpdates: true
  #       foldersFromFilesStructure: true
  defaultDashboardsEnabled: false
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      fastapi:
        gnetId: 18739
        datasource: loki
      app:
        gnetId: 13639
        datasource: loki
      nginx:
        url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
        datasource: default
      nginx-request-handling-performance:
        url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/request-handling-performance.json
        datasource: default        
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: "http://loki:3100"
      version: 1
      basicAuth: false
      isDefault: false

alertmanager:
  enabled: false