grafana:
  admin:
    existingSecret: kube-prometheus-stack-secret
    userKey: GRAFANA_ADMIN_USER
    passwordKey: GRAFANA_ADMIN_PASSWORD
  sidecar:
    datasources:
      enabled: true
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
  # defaultDashboardsEnabled: false
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      fastapi-metrics:
        gnetId: 18739
        revision: 1
        datasource: loki
      app-logs:
        gnetId: 13639
        revision: 1
        datasource: loki
      fastapi:
        file: dashboards/fastapi.json
        datasource: loki
      app:
        file: dashboards/logs.json
        datasource: loki
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: "http://loki:3100"
      version: 2
      orgId: 1
      basicAuth: false
      isDefault: false

alertmanager:
  enabled: false