apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordz.fullname" . }}-celery
  labels:
    {{- include "wordz.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery
spec:
  replicas: {{ .Values.celery.replicaCount }}
  selector:
    matchLabels:
      {{- include "wordz.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery
  template:
    metadata:
      labels:
        {{- include "wordz.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
    spec:
      containers:
        - name: celery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery", "-A", "app.tasks", "worker", "--loglevel=info"]
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: CELERY_METRICS_PORT
              value: {{ .Values.celery.metricsPort | quote }}
          ports:
            - containerPort: {{ .Values.celery.metricsPort }}
              name: metrics
            - name: health
              containerPort: 8080
              protocol: TCP              
          resources:
            {{- toYaml .Values.celery.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10