apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordz.fullname" . }}-celery
  labels:
    {{- include "wordz.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery
spec:
  selector:
    {{- include "wordz.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: celery
  ports:
    - port: {{ .Values.celery.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics