apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordz.fullname" . }}
  labels:
    {{- include "wordz.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: http
      protocol: TCP
  selector:
    {{- include "wordz.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web