nameOverride: ""
fullnameOverride: ""

labels:
  app: fastapi-celery-app
  environment: production

podLabels: {}

selectorLabels:
  app: fastapi-celery-app

replicaCount: 1

image:
  repository: fastapi-celery-app
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8000

celery:
  replicaCount: 3
  metricsPort: 8001
  labels:
    app.kubernetes.io/component: celery
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi


serviceMonitor:
  enabled: true
  namespace: monitoring
  interval: 15s
  additionalLabels:
    release: prometheus

redis:
  host: sample-redis-master.redis
  port: 6379